name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2
  flutter_line_sdk: ^2.4.1
  cupertino_icons: ^1.0.2
  just_audio: ^0.10.5
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/mp3/
    
    
  fonts:
    - family: Daydream
      fonts:
        - asset: assets/fonts/Daydream DEMO.otf
