// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA44KBLuUZrfGMtybiGWuOtKeOlYJXKtSo',
    appId: '1:957561266895:web:c8b4b02c00acb2bd29cdba',
    messagingSenderId: '957561266895',
    projectId: 'rhythmo-8b386',
    authDomain: 'rhythmo-8b386.firebaseapp.com',
    storageBucket: 'rhythmo-8b386.firebasestorage.app',
    measurementId: 'G-VFYXZCSL61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7bSvat30sBXOgfUPNCC-LGENH8KEcY-k',
    appId: '1:957561266895:android:bef182b70a5ae29c29cdba',
    messagingSenderId: '957561266895',
    projectId: 'rhythmo-8b386',
    storageBucket: 'rhythmo-8b386.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOq3j1Hcu_R-1fftFevzKxnzkGqj5udLY',
    appId: '1:957561266895:ios:3a598c711194768229cdba',
    messagingSenderId: '957561266895',
    projectId: 'rhythmo-8b386',
    storageBucket: 'rhythmo-8b386.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOq3j1Hcu_R-1fftFevzKxnzkGqj5udLY',
    appId: '1:957561266895:ios:3a598c711194768229cdba',
    messagingSenderId: '957561266895',
    projectId: 'rhythmo-8b386',
    storageBucket: 'rhythmo-8b386.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA44KBLuUZrfGMtybiGWuOtKeOlYJXKtSo',
    appId: '1:957561266895:web:5da10489ee06448e29cdba',
    messagingSenderId: '957561266895',
    projectId: 'rhythmo-8b386',
    authDomain: 'rhythmo-8b386.firebaseapp.com',
    storageBucket: 'rhythmo-8b386.firebasestorage.app',
    measurementId: 'G-CGV3ZMFY4X',
  );
}
